# yamllint disable rule:line-length
---
name: "Install Minikube"
description: "Installs Minikube"
inputs:
  k8s_version:
    description: 'Minikube Version'
    required: true
  k8s_runtime:
    description: 'Minkube runtime'
    required: false
    default: "docker"
runs:
  using: "composite"
  steps:
    - id: minikube
      run: "${{ github.action_path }}/minikube.sh ${{ inputs.k8s_version }} ${{ inputs.k8s_runtime }}"
      shell: bash
