apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-gcp-gateway
  namespace: default
spec:
  resources:
    requests:
      memory: 50Mi
      cpu: 10m
  replicas: 1
  maxReplicas: 1
