apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-gateway
  namespace: default
spec:
  # setting 'replicas' w/ 'maxReplicas' will configure an autoscaler with
  # min 2 and max 5 replicas.
  replicas: 2
  maxReplicas: 5
  
  # Because everyone has a different OTLP configuration, it is intended
  # that the otlp exporter be modified by the user here. The default
  # configuration has TLS disabled and requires the 'endpoint' to be set.
  config: |
    exporters:
      otlp:
          endpoint: http://bob.com:4433
          tls:
              insecure: true

      logging:

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      # If running within GKE, try to detect the
      # cloud provider, region, availability zone, and k8s.cluster.name.
      resourcedetection:
        detectors: [gke]
        timeout: 2s
        override: false

      batch/metrics:
        send_batch_max_size: 200
        send_batch_size: 200
        timeout: 5s

      batch/logs:
        send_batch_max_size: 200
        send_batch_size: 200
        timeout: 5s

    extensions:
      health_check:

    service:
      extensions:
        - health_check
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - resourcedetection
            - batch/metrics
          exporters:
            - logging
            - otlp

        logs:
          receivers:
            - otlp
          processors:
            - resourcedetection
            - batch/logs
          exporters:
            - logging
            - otlp
