apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: redis
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: observiq-redis
      labels:
        app: redis
      name: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: 80Mi
            cpu: 50m
          requests:
            memory: 50Mi
            cpu: 10m
