apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: redis
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 2
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: observiq-redis
      labels:
        app: redis
      name: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 100m
