# New Relic specific overrides should go in this file for all collectors.
#
# Changes:
# - K8S_CLUSTER 'cluster' --> 'newrelic-poc'
#
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-cluster
  namespace: default
spec:
  env:
    - name: K8S_CLUSTER
      value: "newrelic-poc"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-node
  namespace: default
spec:
  env:
    - name: K8S_CLUSTER
      value: "newrelic-poc"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-redis
  namespace: default
spec:
  env:
    - name: K8S_CLUSTER
      value: "newrelic-poc"
