# New Relic specific overrides should go in this file for all collectors.
#
# Changes:
# - K8S_CLUSTER 'cluster' --> 'newrelic-poc'
#
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-cluster
  namespace: default
spec:
  env:
    - name: K8S_CLUSTER
      value: "newrelic-poc"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-node
  namespace: default
spec:
  env:
    - name: K8S_CLUSTER
      value: "newrelic-poc"
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-redis
  namespace: default
spec:
  env:
    - name: K8S_CLUSTER
      value: "newrelic-poc"
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
