---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-redis
  namespace: default
spec:
  mode: sidecar
  config: |
    receivers:
      redis:
        endpoint: 127.0.0.1:6379
        collection_interval: 60s

    processors:
      # Add k8s metadata to redis metrics
      resource:
        attributes:
        - key: k8s.cluster.name
          value: "${K8S_CLUSTER}"
          action: upsert
        - key: k8s.namespace.name
          value: "${K8S_NAMESPACE}"
          action: upsert
        - key: k8s.pod.name
          value: "${K8S_POD_NAME}"
          action: upsert
        - key: k8s.node.name
          value: "${K8S_NODE_NAME}"
          action: upsert

    exporters:
      otlp:
        endpoint: observiq-gateway:4317
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers:
            - redis
          processors:
            - resource
          exporters:
            - otlp

  image: observiq/observiq-otel-collector:1.5.0
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: K8S_CLUSTER
      value: "cluster"
