apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-node
  namespace: default
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    receivers:
      filelog:
        include:
          - /var/log/containers/*.log
        start_at: end
        exclude:
          # Avoid parsing collectors log to prevent re-parsing parser errors.
          - /var/log/containers/observiq-otel-collector-log-agent-collector*
          # Avoid parsing logging exporter from gateway.
          - /var/log/containers/observiq-otel-collector-gateway-collector*
        poll_interval: 500ms
        resource:
          k8s.node.name: "EXPR(env('K8S_NODE_NAME'))"
          k8s.cluster.name: poc
        operators:
          # Parse the body into a json object
          - type: json_parser
          # Parse the filename into fields
          - type: regex_parser
            # NOTE: The trailing dollar sign is escaped with a second dollar sign
            regex: '^(?P<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?P<namespace>[^_]+)_(?P<container_name>.+)-(?P<container_id>[a-z0-9]{64})\.log$$'
            parse_from: attributes["log.file.name"]

      kubeletstats:
        auth_type: serviceAccount
        collection_interval: 60s
        insecure_skip_verify: true
        k8s_api_config:
          auth_type: serviceAccount
        metric_groups:
        - node
        - pod
        - container

    processors:
      batch:
        send_batch_max_size: 1000
        send_batch_size: 1000
        timeout: 2s

    exporters:
      otlp:
        endpoint: observiq-gateway:4317
        tls:
          insecure: true

    extensions:
      file_storage:
        directory: /var/lib/observiq/otelcol/node

    service:
      extensions:
        - file_storage
      pipelines:
        metrics:
          receivers:
            - kubeletstats
          processors:
            - batch
          exporters:
            - otlp
        logs:
          receivers:
            - filelog
          processors:
            - batch
          exporters:
            - otlp

  image: observiq/observiq-otel-collector:1.2.0
  serviceAccount: observiq-otel-collector
  resources:
    requests:
      memory: 250Mi
      cpu: 250m
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: dockerlogs
      hostPath:
        path: /var/lib/docker/containers
    - name: storage
      hostPath:
        path: /var/lib/observiq/otelcol/node
  volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/docker/containers
      name: dockerlogs
    - mountPath: /var/lib/observiq/otelcol/node
      name: storage
      readOnly: false
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  podSecurityContext:
    runAsUser: 0
