---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-cluster
  namespace: default
spec:
  mode: statefulset
  config: |
    receivers:
      k8s_cluster:
        auth_type: serviceAccount
        collection_interval: 60s

      k8s_events:
    
    processors:
      resource:
        attributes:
        - key: k8s.cluster.name
          value: "${K8S_CLUSTER}"
          action: upsert

      logstransform:
        operators:
          # Remove the node name resource if it is set but empty. Not doing
          # so will cause some platforms (gcp) to identify the log entry as
          # k8s_node resource type.
          - type: remove
            if: resource["k8s.node.name"] == ""
            field: resource["k8s.node.name"]

      batch:
        send_batch_max_size: 1000
        send_batch_size: 1000
        timeout: 2s
  
    exporters:
      otlp:
        endpoint: observiq-gateway:4317
        tls:
          insecure: true

    extensions:
      # Operator wil create the pvc 'default-volume-observiq-cluster-collector-0'
      file_storage:
        directory: /var/lib/observiq/otelcol/cluster

    service:
      extensions:
        - file_storage
      pipelines:
        metrics:
          receivers:
            - k8s_cluster
          processors:
            - resource
            - batch
          exporters:
            - otlp
        logs:
          receivers:
            - k8s_events
          processors:
            - resource
            - logstransform
            - batch
          exporters:
            - otlp

  image: observiq/observiq-otel-collector:1.2.0
  serviceAccount: observiq-otel-collector
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: default-volume-observiq-cluster-collector-0
  volumeMounts:
    - mountPath: /var/lib/observiq/otelcol/cluster
      name:  storage
  env:
    - name: K8S_CLUSTER
      value: "cluster"
  podSecurityContext:
    runAsUser: 0
