name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - "latest"
          - "v1.23.0"
          - "v1.22.0"
          - "v1.21.0"
          - "v1.20.0"
          - "v1.19.0"
          - "v1.18.0"
        format:
          - "docker"
          - "containerd"

    steps:
    - uses: actions/checkout@v2

    - name: Test Deploy
      uses: ./.github/actions/minikube
      with:
        k8s_version: ${{ matrix.k8s-version }}
        k8s_runtime: ${{ matrix.format }}