name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - "v1.23.0"
          - "v1.22.0"
          - "v1.21.0"
        format:
          - "docker"
          - "containerd"

    steps:
    - uses: actions/checkout@v2

    - name: Install Minikube
      uses: ./.github/actions/minikube
      with:
        k8s_version: ${{ matrix.k8s-version }}
        k8s_runtime: ${{ matrix.format }}

    - name: Install Cert Manager
      uses: ./.github/actions/certmanager

    - name: Install OpenTelemetry Operator
      uses: ./.github/actions/opentelemetryoperator

    # We just need a secret that can be mounted, sending telemetry to
    # GCP is not the goal.
    - name: Create Fake GCP Credentials
      run: kubectl create secret generic gcp-credentials --from-literal=ci=true -n default

    - name: Install Kustomize
      run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      shell: bash

    - name: Kustomize Output
      run: kustomize build environments/minikube

    - name: Kustomize Deploy
      run: kustomize build environments/minikube | kubectl apply -f -

    - name: Wait For GCP Gateway Collector
      run: kubectl rollout status statefulset.apps/observiq-gcp-gateway-collector --timeout=60s

    - name: Wait For Cluster Collector
      run: kubectl rollout status statefulset.apps/observiq-cluster-collector --timeout=60s

    - name: Wait For Node Collector
      run: kubectl rollout status daemonset.apps/observiq-node-collector --timeout=60s

    - name: Deploy Redis w/ Side Car Collector
      run: kubectl apply -f app/redis/redis.yaml

    - name: Wait For Redis w/ Side Car Collector
      run: kubectl rollout status deployment.apps/redis --timeout=60s
