name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Install Kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo cp kubeval /usr/local/bin

      - name: Render
        run: |
          kustomize build environments/googlecloud > googlecloud.yaml
          kustomize build environments/newrelic > newrelic.yaml

      - name: Validate GCP
        run: kubeval googlecloud.yaml --ignore-missing-schemas

      - name: Validate New Relic
        run: kubeval newrelic.yaml --ignore-missing-schemas
