name: Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - googlecloud
          - newrelic
          - otlp
    steps:
      - uses: actions/checkout@v2

      - name: Install Kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Install Kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo cp kubeval /usr/local/bin

      - name: Render Manifest
        run: kustomize build environments/${{ matrix.environment }} > ${{ matrix.environment }}.yaml

      - name: Validate Manifest
        run: kubeval ${{ matrix.environment }}.yaml --ignore-missing-schemas
