---
apiVersion: v1
kind: Service
metadata:
  name: observiq-gateway
  namespace: default
  labels:
    app: observiq-gateway
spec:
  ports:
  - port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app: observiq-gateway
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: observiq-gateway
  namespace: default
  labels:
    app: observiq-gateway
spec:
  mode: deployment
  config: |
    receivers:
      prometheus/collector:
        config:
          scrape_configs:
            - job_name: 'observiq-otel-collector'
              scrape_interval: 60s
              static_configs:
                - targets: ['127.0.0.1:8888']
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      # Add k8s metadata to collector metrics
      resource/collector:
        attributes:
        - key: opencensus.resourcetype
          value: pod
          action: upsert
        - key: k8s.cluster.name
          value: poc
          action: upsert
        - key: k8s.cluster.location
          value: us-east1
          action: upsert
        - key: k8s.namespace.name
          value: "${K8S_NAMESPACE}"
          action: upsert
        - key: k8s.pod.name
          value: "${K8S_POD_NAME}"
          action: upsert
        - key: k8s.node.name
          value: "${K8S_NODE_NAME}"
          action: upsert

      batch/metrics:
        send_batch_max_size: 200
        send_batch_size: 200
        timeout: 5s

      batch/logs:
        send_batch_max_size: 200
        send_batch_size: 200
        timeout: 5s
    
    exporters:
      otlp/newrelic:
          endpoint: https://otlp.nr-data.net:443
          headers:
              - api-key: $NEWRELIC_API_KEY
          tls:
              insecure: false

      logging:

    extensions:
      health_check:

    service:
      extensions:
        - health_check
      pipelines:
        # Pipeline for collectors own metrics
        #
        metrics/collector:
          receivers:
            - prometheus/collector
          processors:
            - resource/collector
          exporters:
            - logging
            - otlp/newrelic
        # Pipeline for ingested metrics
        #
        metrics/ingest:
          receivers:
            - otlp
          processors:
            - batch/metrics
          exporters:
            - logging
            - otlp/newrelic
        # Pipeline for ingested logs
        #
        logs:
          receivers:
            - otlp
          processors:
            - batch/logs
          exporters:
            - logging
            - otlp/newrelic

  image: observiq/observiq-otel-collector:1.1.0
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
  env:
    - name: NEWRELIC_API_KEY
      valueFrom:
        secretKeyRef:
          name: newrelic-credentials
          key: api-key
          optional: false
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

